name: cgms_telemetry_spike
publish_to: none
environment:
  sdk: '>=3.13.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  opentelemetry: 0.18.11
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
